create database FPTBook

USE FPTBook

CREATE TABLE Account (
	Username VARCHAR(20) PRIMARY KEY,
	Fullname NVARCHAR(50) NOT NULL,
	Password NVARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Telephone VARCHAR(20) NOT NULL UNIQUE,
	Address VARCHAR(200) NOT NULL,
	Role INT DEFAULT('0') NOT NULL
)

CREATE TABLE Feedback (
	FeedbackID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Username VARCHAR(20) NOT NULL,
	Telephone VARCHAR(20) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Message VARCHAR(1000) NOT NULL,
	DateSend DATETIME NOT NULL,
	FOREIGN KEY(Username) REFERENCES dbo.Account(Username)
)


CREATE TABLE Category (
	CategoryID VARCHAR(10) PRIMARY KEY,
	CategoryName VARCHAR(50) NOT NULL,
	Description VARCHAR(1000) NOT NULL
)

CREATE TABLE Author (
	AuthorID VARCHAR(10) PRIMARY KEY,
	AuthorName VARCHAR(50) NOT NULL,
	Description VARCHAR(1000) NOT NULL
)
CREATE TABLE Publisher (
	PublisherID VARCHAR(10) PRIMARY KEY,
	PublisherName VARCHAR(50) NOT NULL,
	Description VARCHAR(1000) NOT NULL
)

CREATE TABLE Book (
	BookID VARCHAR(10) PRIMARY KEY,
	BookName NVARCHAR(100) NOT NULL,
	CategoryID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Category(CategoryID),
	AuthorID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Author(AuthorID),
	PublisherID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Publisher(PublisherID),
	Price BIGINT NOT NULL,
	Quantity INT NOT NULL,
	Image NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL
)


CREATE TABLE Orders (
	OrderID INT IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES dbo.Account(Username),
	Telephone VARCHAR(20) NOT NULL,
	Fullname NVARCHAR(50) NOT NULL,
	DeliveyAddress VARCHAR(100) NOT NULL,
	OrderDate DATETIME NOT NULL,
	TotalPrice INT NOT NULL,
	)

CREATE TABLE OrderDetail(
	OrderID INT NOT NULL FOREIGN KEY REFERENCES dbo.Orders(OrderID) ON DELETE CASCADE,
	BookID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES dbo.Book(BookID),
	Quantity INT NOT NULL,
	Price BIGINT NOT NULL,
	Subtotal BIGINT NOT NULL,
	PRIMARY KEY (OrderID, BookID)
)
